### PR TITLE
Add a method to expose the proxy protocol destination address.

### PR DESCRIPTION
**Pull request by tomwilkie**
Alternatively, we could expose it as part of `LocalAddr()`, similar to `RemoteAddr()`.  WDYT?

### CODE REVIEW

**Comment by pquerna** [comment]
This should be `conn.LocalAddr()`, since thats what the proxy protocol line is telling us IMO

**Comment by bboreham** [comment]
Rebased and updated in line with your feedback.  I left the two commits so it's clear who did what.

**Comment by bboreham** [comment]
@armon @pquerna any further thoughts?

**Comment by armon** [comment]
LGTM!

**Pull request merged**
